DEFAULT_PROFILE = {
    "structure_tf": "H1",
    "structure_bars": 300,
    "entry_tf": "M15",
    "entry_bars": 150,
    "support_bias_tf": None,
    "support_bias_bars": 0,
    "pair_limit": 1,
    "risk_per_trade": 0.01,
    "min_execution_rr": 1.2,
    "kill_switch_min_bars": 4,
    "kill_switch_atr_break_mult": 0.15,
    "market_structure": {
        "DISPLACEMENT_ATR_MULT": 1.2,
        "LOW_VOL_RATIO": 0.7,
        "HIGH_VOL_RATIO": 1.6,
        "MIN_SWING_ATR_MULT": 0.6,
        "PRESSURE_MIN_MOVE_ATR": 1.2,
        "PRESSURE_MIN_BAR_COUNT": 3,
    },
    "liquidity": {
        "lookback": 20,
        "SWEEP_STRENGTH_MIN": 0.20,
        "BODY_DOMINANCE_MIN": 0.30,
        "EQ_TOL_ATR_MULT": 0.15,
        "LOW_VOL_SKIP_RATIO": 0.60,
    },
    "displacement": {
        "impulse_atr_mult": 1.2,
        "lookback_candles": 3,
    },
    "ob_breaker": {
        "level_pad_atr_mult": 0.20,
        "lookback": 30,
        "search_back": 12,
    },
    "execution_levels": {
        "min_stop_atr_mult": 0.35,
        "min_stop_price": 0.0,
        "min_stop_points": 500,
        "anchor_buffer_atr_mult": 0.0,
        "anchor_buffer_price": 0.0,
    },
}
